name: zerotier
description: ZeroTier in Dart.
version: 0.0.1-dev.1
repository: https://github.com/ManyMath/zerotier-dart

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
